spring:
  application:
    name: cv-auth-service

  cloud:
    config:
      uri: http://localhost:8061

  profiles:
    active: default

  config:
    import: optional:configserver:${spring.cloud.config.uri}

jwt:
  secret: your-256-bit-base64-encoded-key
  expiration: 3600000