spring:
  cloud:
    config:
      uri: http://103.168.18.176:8061

  config:
    import: optional:configserver:${spring.cloud.config.uri}

ADMIN_SERVICE_URL: http://localhost:8071
OWNER_SERVICE_URL: http://localhost:8072